# Use an official Node.js runtime as a parent image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . ./

RUN mkdir -p /mnt/data

# Expose the port the app runs on
EXPOSE 5000

# Start the app
CMD ["npm", "start"]